### ISSUE TITLE
NullPointerException after undoing a tile placement

### ISSUE THREAD

**Issue by voveve** [farin/JCloisterZone#212]
I cmd+z a tile placement, lagged a bit (slow old Mac) and cmd+z a few more times

red band saying NullPointerException popped up in the top of the window
can't place tile, can't send chat message

tried to save to load and see if it was goin' to be fixed = the game wasn't saved even if it seemed to have done it

I pasted down below the error.log file inherent, hoping it will help :) 

```

[Thread-2] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.game.Game.undo(Game.java:186)
    at com.jcloisterzone.ui.ClientMessageListener.handleUndo(ClientMessageListener.java:518)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:36)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-2] ERROR com.jcloisterzone.ui.ClientMessageListener - null
java.lang.NullPointerException
    at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.ui.ClientMessageListener.handleRmi(ClientMessageListener.java:504)
    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:36)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-2] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-2] ERROR com.jcloisterzone.ui.ClientMessageListener - null
java.lang.NullPointerException
    at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.ui.ClientMessageListener.handleRmi(ClientMessageListener.java:504)
    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:36)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-2] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-2] ERROR com.jcloisterzone.ui.ClientMessageListener - null
java.lang.NullPointerException
    at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.ui.ClientMessageListener.handleRmi(ClientMessageListener.java:504)
    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:36)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-2] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-2] ERROR com.jcloisterzone.ui.ClientMessageListener - null
java.lang.NullPointerException
    at sun.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.ui.ClientMessageListener.handleRmi(ClientMessageListener.java:504)
    at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:36)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-2] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-5] ERROR com.jcloisterzone.game.phase.ActionPhase - Method 'placeTile' called in invalid state
[Thread-5] ERROR com.jcloisterzone.game.phase.ActionPhase - Method 'placeTile' called in invalid state
[Thread-5] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.game.Game.undo(Game.java:186)
    at com.jcloisterzone.ui.ClientMessageListener.handleUndo(ClientMessageListener.java:518)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:36)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.handleGameStarted(ClientMessageListener.java:271)
    at com.jcloisterzone.ui.ClientMessageListener.handleGame(ClientMessageListener.java:336)
    at com.jcloisterzone.ui.ClientMessageListener.handleGame(ClientMessageListener.java:290)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:36)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-5] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-5] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-5] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-5] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-5] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-5] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-5] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
[Thread-5] ERROR com.jcloisterzone.ui.view.GameView - NullPointerException
java.lang.NullPointerException
    at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:26)
    at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:20)
    at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:143)
    at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:100)
    at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
    at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
    at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
    at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Reloecc** [comment]
Same happend to us right now. We were play online, on oficcial server (If I can call it that). I pressed ctrl+z twice in rapid succession. Null pointer exception alert message poped up, game unsaveable.
