### ISSUE TITLE
update requirements doc to Java 8

### ISSUE THREAD

**Issue by kotc** [farin/JCloisterZone#245]
- more info:
java version "1.7.0_151"
OpenJDK Runtime Environment (IcedTea 2.6.11) (7u151-2.6.11-1~deb8u1)
OpenJDK Client VM (build 24.151-b01, mixed mode, sharing)
- error stack:

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/jcloisterzone/ui/JCloisterZone : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by farin** [comment]
@kotc current requirement is Java 8, there is mistake in docs, changing issue title

**Comment by kotc** [comment]
hmm, is there a chance to make it jdk1.7 compatible?

**Comment by farin** [comment]
Sorry but it's not possible. Especially for upcoming jcz 4.0. It's based on vavr.io and use lot's of Java 8 features (which are very useful and brings lot of value)

And finally Java 8 exists since 2014. that's a lot of time
