### ISSUE TITLE
Message ... hasn't been handled by ... phase. (= not delivered message)

### ISSUE THREAD

**Issue by ScardracS** [farin/JCloisterZone#258]
When I play with my GF the game stops working (I play on my house and she in her). She loose connection more frequently than me, but that's issue is much annoying. We have cecked both mine and here connection and everything works as expected. What that could be? Have you any idea?

**Comment by farin** [comment]
Are you using version 4.1.1? (there is important networking reliability improvement)

**Comment by ScardracS** [comment]
Yes, se both use 4.1.1

**Comment by farin** [comment]
What exactly happens? When connection is lost it should be automatically restored.

I still not sure if issue is cause by some issue introduced in 4.x branch or just more people use app.
Versions 3.x was reliable with no networking issue reports. Since 4.1.1, networking library was reverted to version used in 3.x due some major issues. So now I would expect same reliability like for old branch.

**Comment by ScardracS** [comment]
When she loose connection the game doesn't reconnect anymore and sometimes it told an error (next time we play i'll post more info)

**Comment by ScardracS** [comment]
That's the error: Amore ❤️❤️❤️:
Message PlaceTileMessage hasn't been handled by ActionPhase phase.

**Comment by farin** [comment]
I can confirm it. Also it can be sometimes observed also on local game, which is still using networking (eg with 6 clients connected together)

It caused by lost message, which cause usually missing placed follower on on client and desynced game state on clients.

I am going to add some check to prevent such situation.

**Comment by farin** [comment]
Probably completely different reason for this - there is major issue related to barn meeple - with badly generated id it share it with pig and these meeples are misplaced during remote games.

But I am going to verify it for sure.

**Comment by ScardracS** [comment]
We still have problems, but only if we play with Windows. I've tried with Ubuntu and archlinux (with openjdk) and it works perfectly. Could this is the problem? What do you think?

**Comment by farin** [comment]
Are you sure you are using latest 4.2.1 on windows?

Different behavior on Win platform is in general possible, but i thinks that causing this issuse is improbable. 4.2+ has mechanism which verifies that no message was lost on network (is such case it should reconnect or show different kind of error)

When it happens, it's good idea always save game and provide it to examination. Also information if it is reproducible by loading such game is useful information for me. + you can look if error.log was created (it should be in same folder as your config.yaml)

**Comment by ScardracS** [comment]
I'll post it asap

**Comment by ScardracS** [comment]
[Thread-1] WARN com.jcloisterzone.ui.ClientMessageListener - Unexpected state - should never happen

**Comment by ScardracS** [comment]
[Thread-1] WARN com.jcloisterzone.ui.ClientMessageListener - No controller for message com.jcloisterzone.wsio.message.ClientUpdateMessage@1f263909
[Thread-1] WARN com.jcloisterzone.ui.ClientMessageListener - Unexpected state - should never happen
[Thread-1] WARN com.jcloisterzone.ui.ClientMessageListener - No controller for message com.jcloisterzone.wsio.message.ClientUpdateMessage@71c54e2c
[Thread-1] WARN com.jcloisterzone.ui.ClientMessageListener - No controller for message com.jcloisterzone.wsio.message.ClientUpdateMessage@5460b423
[Thread-4] WARN com.jcloisterzone.game.GameStatePhaseReducer - Unhandled message:
	{"type":"PLACE_TILE","payload":{"gameId":"LAk0skBG7i4WYWECRULf6eijnsj+","messageId":"1.ActionPhase.0","tileId":"BA.RRR","rotation":"R0","position":[1,7]}}
[Thread-4] ERROR com.jcloisterzone.ui.Client - Message PlaceTileMessage hasn't been handled by ActionPhase phase.
java.lang.IllegalArgumentException: Message PlaceTileMessage hasn't been handled by ActionPhase phase.
	at com.jcloisterzone.game.GameStatePhaseReducer.applyMessageOnPhase(GameStatePhaseReducer.java:153)
	at com.jcloisterzone.game.GameStatePhaseReducer.apply(GameStatePhaseReducer.java:168)
	at com.jcloisterzone.game.Game.start(Game.java:382)
	at com.jcloisterzone.ui.ClientMessageListener.handleGameStarted(ClientMessageListener.java:223)
	at com.jcloisterzone.ui.ClientMessageListener.handleGame(ClientMessageListener.java:300)
	at com.jcloisterzone.ui.ClientMessageListener.handleGame(ClientMessageListener.java:248)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:38)
	at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:21)
	at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:137)
	at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:106)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by ScardracS** [comment]
Last error message with v4.3.0
