### ISSUE TITLE
Error when reconnecting

### ISSUE THREAD

**Issue by jeandeaual** [farin/JCloisterZone#259]
While playing online with version 4.1.1 and the bazaar expansion, during the bidding phase, one of the player didn't get any prompt to raise the bid or pass.
Since he couldn't do anything else, he tried to leave the game and then reconnect, which didn't work and left the following error message in `error.log`:

```
[Thread-4] ERROR com.jcloisterzone.ui.Client - Message PlaceTileMessage hasn't been handled by ActionPhase phase.
java.lang.IllegalArgumentException: Message PlaceTileMessage hasn't been handled by ActionPhase phase.
	at com.jcloisterzone.game.GameStatePhaseReducer.applyMessageOnPhase(GameStatePhaseReducer.java:143)
	at com.jcloisterzone.game.GameStatePhaseReducer.apply(GameStatePhaseReducer.java:158)
	at com.jcloisterzone.game.Game.start(Game.java:382)
	at com.jcloisterzone.ui.ClientMessageListener.handleGameStarted(ClientMessageListener.java:220)
	at com.jcloisterzone.ui.ClientMessageListener.handleGame(ClientMessageListener.java:284)
	at com.jcloisterzone.ui.ClientMessageListener.handleGame(ClientMessageListener.java:232)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.jcloisterzone.wsio.MessageDispatcher.dispatchOn(MessageDispatcher.java:38)
	at com.jcloisterzone.wsio.MessageDispatcher.dispatch(MessageDispatcher.java:21)
	at com.jcloisterzone.ui.ClientMessageListener.onWebsocketMessage(ClientMessageListener.java:135)
	at com.jcloisterzone.wsio.WebSocketConnection$WebSocketClientImpl.onMessage(WebSocketConnection.java:96)
	at org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:248)
	at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:375)
	at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:158)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:185)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by farin** [comment]
seems to be duplicate to #258
