### ISSUE TITLE
File loading problem if username contains special characters

### ISSUE THREAD

**Issue by kitlei-robert** [farin/JCloisterZone#279]
The program fails if the username contains a special character such as an exclamation mark (!), as it cannot load its data, plugins, etc. The program repeatedly tries to access the directory without the special character (MyUser instead of MyUser!), which obviously fails. See a relevant section of error.log below.

---------------------

[main] INFO com.jcloisterzone.ui.JCloisterZone - Data directory C:\Users\MyUser!\Downloads\JCloisterZone-4.4.1\JCloisterZone
[main] ERROR com.jcloisterzone.ui.JCloisterZone - C:\Users\MyUser (The system cannot find the file specified)
java.io.FileNotFoundException: C:\Users\MyUser (The system cannot find the file specified)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:94)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152)
	at java.net.URL.openStream(URL.java:1045)
	at com.jcloisterzone.ui.JCloisterZone.run(JCloisterZone.java:220)
	at com.jcloisterzone.ui.JCloisterZone.main(JCloisterZone.java:278)

**Comment by farin** [comment]
hopefully not issue for new Electron based 5.x client
