### ISSUE TITLE
Multiple Pigs in game

### ISSUE THREAD

**Issue by stanolacko** [farin/JCloisterZone#404]
How to deal multiple pigs on fields
1. No changes - pigs do not stack - so if player has at least one pig on field he gets +1 per city doesn't matter how much pigs are on field
2. Get +1 per each pig on field

Maybe some bug is there, check attached save game ended with
```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
        at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:756)
        at java.base/java.util.ArrayList.add(ArrayList.java:481)
        at com.jcloisterzone.feature.Field.getCityPoints(Field.java:172)
        at com.jcloisterzone.feature.Field.getPoints(Field.java:116)
        at com.jcloisterzone.reducers.ScoreField.getFeaturePoints(ScoreField.java:26)
        at com.jcloisterzone.reducers.ScoreFeature.apply(ScoreFeature.java:88)
        at com.jcloisterzone.reducers.FinalScoring.apply(FinalScoring.java:85)
        at com.jcloisterzone.game.phase.GameOverPhase.enter(GameOverPhase.java:18)
        at com.jcloisterzone.game.GameStatePhaseReducer.applyStepResult(GameStatePhaseReducer.java:134)
        at com.jcloisterzone.game.GameStatePhaseReducer.apply(GameStatePhaseReducer.java:144)
        at com.jcloisterzone.engine.Engine.run(Engine.java:263)
        at com.jcloisterzone.engine.Engine.main(Engine.java:337)
```
[error-multipleissues.zip](https://github.com/farin/JCloisterZone/files/6988410/error-multipleissues.zip)

**Comment by stanolacko** [comment]
So resulution can be easy, if player have pig +1. doesn't matter how much pigs.
So pig do not stack.
