### ISSUE TITLE
GPU process isn't usable - game won't start

### ISSUE THREAD

**Issue by t3d** [farin/JCloisterZone#427]
since around the version 5.8, I have a following issue when I try to run the game:

> $ ./jcloisterzone-5.10.1.AppImage 
Loading settings from /home/tomasz/.config/jcloisterzone/jcz-config.json
13:15:25.601 › Checking for update
Error occurred in handler for 'update-menu': TypeError: Cannot read property 'getMenuItemById' of undefined
    at /tmp/.mount_jcloiskOkyQB/resources/app/dist/main/index.js:4:110471
    at Array.forEach (<anonymous>)
    at /tmp/.mount_jcloiskOkyQB/resources/app/dist/main/index.js:4:110443
    at electron/js2c/browser_init.js:197:579
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9782)
    at Object.emit (events.js:315:20)
Error occurred in handler for 'update-menu': TypeError: Cannot read property 'getMenuItemById' of undefined
    at /tmp/.mount_jcloiskOkyQB/resources/app/dist/main/index.js:4:110471
    at Array.forEach (<anonymous>)
    at /tmp/.mount_jcloiskOkyQB/resources/app/dist/main/index.js:4:110443
    at electron/js2c/browser_init.js:197:579
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9782)
    at Object.emit (events.js:315:20)
[19157:0204/131527.144053:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

This happens on Fedora 35, fully upgraded. Other electron-based apps work just fine (Teams). Maybe this is releated to hardware, because there are 2 GPUs on this laptop:
> $ lspci | grep "VGA\\|3D"
00:02.0 VGA compatible controller: Intel Corporation CoffeeLake-H GT2 [UHD Graphics 630]
01:00.0 3D controller: NVIDIA Corporation GM108M [GeForce MX130] (rev a2)

**Comment by t3d** [comment]
After doing some research I found out that the game starts when run with
--in-process-gpu
flag.
